packages:
  - "apps/*"
  - "packages/*"
  - "packages/core/*"

allowBuilds:
  sharp: true
  esbuild: true
  unrs-resolver: true
  '@sentry/cli': true

overrides:
  "@types/react": "19.1.6"
  "@types/react-dom": "19.1.5"
