import {
  getCountryLabel,
  getSongLanguageLabel,
} from "../profilePresentation";
import type { StorySectionDefinition } from "./types";

/**
 * Registre des sections du Story Engine.
 * Ajouter une section ici — aucun changement UI requis.
 */
export const STORY_SECTION_DEFINITIONS: StorySectionDefinition[] = [
  {
    id: "my_story",
    title: "Mon histoire",
    icon: "📖",
    group: "narrative",
    audience: "all",
    order: 10,
    evolutionSource: "profile_static",
    emptyHint: "La musique commence toujours par une histoire — la vôtre mérite d'être entendue.",
    editPlaceholder: "Racontez votre parcours, vos débuts, ce qui vous a mené à la musique…",
    resolveFromProfile: (ctx) => ctx.profile.bio?.trim() || null,
  },
  {
    id: "why_music",
    title: "Pourquoi je fais de la musique",
    icon: "💚",
    group: "narrative",
    audience: "all",
    order: 20,
    evolutionSource: "user_draft",
    emptyHint: "Qu'est-ce qui vous pousse à créer ou à écouter ? Partagez votre motivation.",
    editPlaceholder: "Expliquez ce que la musique représente pour vous…",
    resolveFromProfile: () => null,
  },
  {
    id: "inspirations",
    title: "Mes inspirations",
    icon: "✨",
    group: "narrative",
    audience: "all",
    order: 30,
    evolutionSource: "user_draft",
    emptyHint: "Vos inspirations nourrissent votre univers — décrivez ceux qui vous ont éveillé.",
    editPlaceholder: "Artistes, moments, sons qui vous inspirent…",
    resolveFromProfile: () => null,
  },
  {
    id: "influences",
    title: "Mes influences",
    icon: "🎵",
    group: "narrative",
    audience: "artist",
    order: 40,
    evolutionSource: "profile_static",
    emptyHint: "Vos influences façonnent votre signature musicale.",
    editPlaceholder: "Genres, styles, artistes qui ont marqué votre son…",
    resolveFromProfile: (ctx) => ctx.profile.main_genre?.trim() || null,
  },
  {
    id: "first_stage",
    title: "Ma première scène",
    icon: "🎤",
    group: "narrative",
    audience: "artist",
    order: 50,
    evolutionSource: "user_draft",
    emptyHint: "Votre premier pas sur scène reste gravé — racontez ce moment.",
    editPlaceholder: "Où et quand avez-vous performé pour la première fois ?",
    resolveFromProfile: () => null,
  },
  {
    id: "goals",
    title: "Mes objectifs",
    icon: "🎯",
    group: "narrative",
    audience: "all",
    order: 60,
    evolutionSource: "user_draft",
    emptyHint: "Où souhaitez-vous emmener votre musique dans les prochains mois ?",
    editPlaceholder: "Vos objectifs concrets pour votre parcours…",
    resolveFromProfile: () => null,
  },
  {
    id: "dream",
    title: "Mon rêve",
    icon: "🌟",
    group: "narrative",
    audience: "all",
    order: 70,
    evolutionSource: "user_draft",
    emptyHint: "Chaque grand artiste a commencé par un rêve — quel est le vôtre ?",
    editPlaceholder: "Le rêve qui vous guide, Guinée → Afrique → Monde…",
    resolveFromProfile: () => null,
  },
  {
    id: "community_message",
    title: "Mon message à ma communauté",
    icon: "💬",
    group: "narrative",
    audience: "all",
    order: 80,
    evolutionSource: "user_draft",
    emptyHint: "Votre histoire inspirera peut-être d'autres créateurs.",
    editPlaceholder: "Un mot pour vos fans, votre famille musicale…",
    resolveFromProfile: () => null,
  },
  {
    id: "origin_city",
    title: "Ville d'origine",
    icon: "📍",
    group: "roots",
    audience: "all",
    order: 110,
    evolutionSource: "profile_static",
    emptyHint: "Votre ville ancre votre histoire dans un territoire vivant.",
    editPlaceholder: "Conakry, Labé, Kankan…",
    resolveFromProfile: (ctx) => ctx.profile.city?.trim() || null,
  },
  {
    id: "prefecture",
    title: "Préfecture",
    icon: "🗺️",
    group: "roots",
    audience: "all",
    order: 120,
    evolutionSource: "user_draft",
    emptyHint: "Précisez votre préfecture pour ancrer votre récit guinéen.",
    editPlaceholder: "Nom de votre préfecture…",
    resolveFromProfile: () => null,
  },
  {
    id: "region",
    title: "Région",
    icon: "🇬🇳",
    group: "roots",
    audience: "all",
    order: 130,
    evolutionSource: "profile_static",
    emptyHint: "Votre région porte des sonorités et des traditions uniques.",
    editPlaceholder: "Région naturelle ou administrative…",
    resolveFromProfile: (ctx) => ctx.profile.origin_region?.trim() || null,
  },
  {
    id: "languages_spoken",
    title: "Langues parlées",
    icon: "🗣️",
    group: "roots",
    audience: "all",
    order: 140,
    evolutionSource: "profile_static",
    emptyHint: "Soussou, Pular, Malinké, Français — vos langues sont votre force.",
    editPlaceholder: "Langues que vous parlez ou chantez…",
    resolveFromProfile: (ctx) => {
      const parts: string[] = [];
      const songLang = getSongLanguageLabel(ctx.profile.song_language);
      if (songLang) parts.push(songLang);
      if (ctx.profile.preferred_language?.trim()) {
        parts.push(ctx.profile.preferred_language.trim());
      }
      const country = getCountryLabel(ctx.profile.country_code);
      if (country && parts.length === 0) parts.push(country);
      return parts.length > 0 ? parts.join(" · ") : null;
    },
  },
  {
    id: "first_musical_influences",
    title: "Premières influences musicales",
    icon: "🪘",
    group: "roots",
    audience: "all",
    order: 150,
    evolutionSource: "user_draft",
    emptyHint: "Djembé, afrobeat, mandingue… quelles sonorités vous ont formé ?",
    editPlaceholder: "Vos premières découvertes musicales guinéennes…",
    resolveFromProfile: () => null,
  },
  {
    id: "musical_culture",
    title: "Culture musicale",
    icon: "🎭",
    group: "roots",
    audience: "all",
    order: 160,
    evolutionSource: "user_draft",
    emptyHint: "Décrivez la culture musicale qui vous entoure et vous inspire.",
    editPlaceholder: "Festivals, scènes locales, traditions de votre environnement…",
    resolveFromProfile: () => null,
  },
  {
    id: "traditions",
    title: "Traditions",
    icon: "🌿",
    group: "roots",
    audience: "all",
    order: 170,
    evolutionSource: "user_draft",
    emptyHint: "Les traditions guinéennes enrichissent chaque création authentique.",
    editPlaceholder: "Rituels, cérémonies, héritages culturels liés à votre musique…",
    resolveFromProfile: () => null,
  },
];
