import type { JourneyStepDefinition } from "./types";

/**
 * Registre central des étapes du parcours SONAFRIK.
 * Ajouter une étape ici suffit — aucun changement UI requis.
 */
export const PROFILE_JOURNEY_STEPS: JourneyStepDefinition[] = [
  {
    id: "account_created",
    icon: "🌱",
    title: "Création du compte",
    shortLabel: "Compte créé",
    audience: "all",
    order: 10,
    evaluate: () => true,
  },
  {
    id: "profile_basics",
    icon: "📝",
    title: "Profil complété",
    shortLabel: "Profil complété",
    audience: "all",
    order: 20,
    prerequisiteIds: ["account_created"],
    evaluate: (ctx) => {
      if (ctx.isArtist) {
        return !!(ctx.profile.stage_name?.trim() || ctx.profile.full_name?.trim()) &&
          !!ctx.profile.city?.trim();
      }
      return !!ctx.profile.full_name?.trim() && !!ctx.profile.city?.trim();
    },
    action: { label: "Compléter mon profil", href: "/profile/edit" },
    whyImportant: "Un profil complet inspire confiance à toute la communauté SONAFRIK.",
    benefits: [
      "Meilleure visibilité dans les recherches",
      "Confiance renforcée auprès des auditeurs",
    ],
  },
  {
    id: "profile_photo",
    icon: "📸",
    title: "Photo de profil ajoutée",
    shortLabel: "Photo de profil",
    audience: "all",
    order: 30,
    prerequisiteIds: ["profile_basics"],
    evaluate: (ctx) => !!(ctx.profile.avatar_url || ctx.profile.avatar_path),
    action: { label: "Ajouter ma photo", href: "/profile/edit" },
    whyImportant: "Votre visage est la première connexion avec vos futurs fans.",
    benefits: ["Profil plus humain et mémorable", "Taux de clics plus élevé sur votre page"],
  },
  {
    id: "cover_photo",
    icon: "🖼️",
    title: "Photo de couverture ajoutée",
    shortLabel: "Couverture",
    audience: "artist",
    order: 40,
    prerequisiteIds: ["profile_photo"],
    evaluate: () => false,
    action: { label: "Personnaliser ma couverture", href: "/profile/edit" },
    whyImportant: "Une couverture soignée transforme votre page en véritable vitrine.",
    benefits: ["Identité visuelle forte", "Page artiste premium"],
  },
  {
    id: "bio_completed",
    icon: "✍️",
    title: "Bio complétée",
    shortLabel: "Bio",
    audience: "all",
    order: 50,
    prerequisiteIds: ["profile_photo"],
    evaluate: (ctx) => !!ctx.profile.bio?.trim(),
    action: { label: "Rédiger ma bio", href: "/profile/edit" },
    whyImportant: "Votre histoire donne envie de vous écouter et de vous suivre.",
    benefits: ["Connexion émotionnelle avec les auditeurs", "Différenciation sur la scène"],
  },
  {
    id: "first_track",
    icon: "🎵",
    title: "Premier morceau publié",
    shortLabel: "Premier morceau",
    audience: "artist",
    order: 60,
    prerequisiteIds: ["bio_completed"],
    evaluate: (ctx) => (ctx.activity.publishedTracks ?? 0) > 0,
    action: { label: "Publier maintenant", href: "/creator/catalog/tracks" },
    whyImportant: "Les artistes ayant publié un morceau sont beaucoup plus visibles.",
    benefits: [
      "Apparition dans le catalogue SONAFRIK",
      "Début du comptage des écoutes et royalties",
    ],
  },
  {
    id: "first_listen_artist",
    icon: "🎧",
    title: "Première écoute",
    shortLabel: "Première écoute",
    audience: "artist",
    order: 70,
    prerequisiteIds: ["first_track"],
    evaluate: () => false,
    action: { label: "Partager mon morceau", href: "/creator/catalog/tracks" },
    whyImportant: "Votre première écoute marque le début de votre impact sur la scène.",
    benefits: ["Statistiques d'audience activées", "Début du parcours royalties"],
  },
  {
    id: "first_listen_listener",
    icon: "🎧",
    title: "Première écoute",
    shortLabel: "Première écoute",
    audience: "listener",
    order: 70,
    prerequisiteIds: ["bio_completed"],
    evaluate: () => false,
    action: { label: "Explorer la musique", href: "/listen" },
    whyImportant: "Chaque écoute nourrit l'écosystème musical guinéen.",
    benefits: ["Découverte de nouveaux talents", "Historique d'écoute personnalisé"],
  },
  {
    id: "first_fan",
    icon: "❤️",
    title: "Premier fan",
    shortLabel: "Premier fan",
    audience: "artist",
    order: 80,
    prerequisiteIds: ["first_track"],
    evaluate: () => false,
    action: { label: "Partager mon profil", href: "/profile" },
    whyImportant: "Votre premier fan est le début d'une communauté fidèle.",
    benefits: ["Notifications de nouvelles sorties", "Base d'audience engagée"],
  },
  {
    id: "first_playlist",
    icon: "📋",
    title: "Première playlist",
    shortLabel: "Première playlist",
    audience: "listener",
    order: 80,
    prerequisiteIds: ["first_listen_listener"],
    evaluate: () => false,
    action: { label: "Créer une playlist", href: "/library" },
    whyImportant: "Organiser vos morceaux préférés enrichit votre expérience d'écoute.",
    benefits: ["Accès rapide à vos titres favoris", "Partage avec vos proches"],
  },
  {
    id: "first_collaboration",
    icon: "🤝",
    title: "Première collaboration",
    shortLabel: "Collaboration",
    audience: "artist",
    order: 90,
    prerequisiteIds: ["first_track"],
    evaluate: () => false,
    action: { label: "Découvrir les artistes", href: "/listen" },
    whyImportant: "Les collaborations font grandir la scène musicale guinéenne.",
    benefits: ["Nouveaux publics croisés", "Crédits partagés sur vos sorties"],
  },
  {
    id: "first_verification",
    icon: "✅",
    title: "Première vérification",
    shortLabel: "Vérification",
    audience: "artist",
    order: 100,
    prerequisiteIds: ["first_track"],
    evaluate: () => false,
    action: { label: "Demander la vérification", href: "/creator/verification" },
    whyImportant: "Le badge vérifié rassure les auditeurs et les partenaires.",
    benefits: ["Badge officiel SONAFRIK", "Accès aux fonctionnalités avancées"],
  },
  {
    id: "first_revenue",
    icon: "💰",
    title: "Premier revenu",
    shortLabel: "Premier revenu",
    audience: "artist",
    order: 110,
    prerequisiteIds: ["first_listen_artist"],
    evaluate: () => false,
    action: { label: "Voir mon wallet", href: "/wallet" },
    whyImportant: "Vos écoutes se transforment en revenus transparents.",
    benefits: ["Suivi financier en temps réel", "Royalties automatiques"],
  },
  {
    id: "first_withdrawal",
    icon: "🏦",
    title: "Premier retrait",
    shortLabel: "Premier retrait",
    audience: "artist",
    order: 120,
    prerequisiteIds: ["first_revenue"],
    evaluate: () => false,
    action: { label: "Configurer un retrait", href: "/wallet/payout" },
    whyImportant: "Récupérer vos gains concrétise votre carrière musicale.",
    benefits: ["Paiement vers Orange Money ou MTN", "Historique sécurisé"],
  },
  {
    id: "first_album",
    icon: "💿",
    title: "Premier album",
    shortLabel: "Premier album",
    audience: "artist",
    order: 130,
    prerequisiteIds: ["first_track"],
    evaluate: (ctx) => (ctx.activity.publishedAlbums ?? 0) > 0,
    action: { label: "Publier un album", href: "/creator/catalog/releases" },
    whyImportant: "Un album marque une étape majeure dans la carrière d'un artiste.",
    benefits: ["Présence renforcée dans le catalogue", "Expérience d'écoute immersive"],
  },
  {
    id: "first_concert",
    icon: "🎤",
    title: "Premier concert annoncé",
    shortLabel: "Premier concert",
    audience: "artist",
    order: 140,
    prerequisiteIds: ["first_album"],
    evaluate: () => false,
    action: { label: "Préparer ma scène", href: "/creator" },
    whyImportant: "Le live connecte votre musique à votre public en personne.",
    benefits: ["Visibilité événementielle", "Lien direct avec vos fans"],
  },
];
