"use client";

import { memo, useCallback } from "react";
import type { Album, Track } from "@sonafrik/types";
import {
  formatPublicationDate,
  formatTrackDuration,
  isAutoGeneratedCover,
} from "@sonafrik/api/catalog";
import { CoverImage } from "@/components/CoverImage";
import { PublicationStatusBadge } from "./PublicationStatusBadge";

function PublicationCardInner({
  track,
  album,
  onSelect,
}: {
  track: Track;
  album?: Album;
  onSelect: (track: Track) => void;
}) {
  const autoCover = album ? isAutoGeneratedCover(album) : false;
  const handleClick = useCallback(() => onSelect(track), [onSelect, track]);

  return (
    <button
      type="button"
      className="pub-card"
      onClick={handleClick}
      aria-label={`Ouvrir la fiche de ${track.title}`}
    >
      <div className="pub-card__cover">
        {album?.cover_path ? (
          <CoverImage coverPath={album.cover_path} alt="" imgSizes="56px" />
        ) : (
          <span className="pub-card__cover-placeholder" aria-hidden="true">
            🎵
          </span>
        )}
      </div>

      <div className="pub-card__body">
        <p className="pub-card__title">{track.title}</p>
        <p className="pub-card__meta">
          {formatTrackDuration(track.duration_seconds)} · Mis à jour le{" "}
          {formatPublicationDate(track.updated_at)}
        </p>
        {autoCover ? (
          <p className="pub-card__hint">Pochette automatique SONAFRIK</p>
        ) : null}
      </div>

      <PublicationStatusBadge status={track.publication_status} />
    </button>
  );
}

export const PublicationCard = memo(PublicationCardInner);
