"use client";

import { useCallback, useEffect, useRef } from "react";
import type { Album, Track } from "@sonafrik/types";
import {
  buildPublicationLifecycleTimeline,
  formatPublicationDate,
  formatTrackDuration,
} from "@sonafrik/api/publication-library";
import { isAutoGeneratedCover } from "@sonafrik/api/catalog";
import { CoverImage } from "@/components/CoverImage";
import { PublicationStatusBadge } from "./PublicationStatusBadge";
import { PublicationContextualActions } from "./PublicationContextualActions";
async function sharePublication(track: Track, albumId?: string | null): Promise<void> {
  const text = `Écoutez « ${track.title} » sur SONAFRIK`;
  const origin = typeof window !== "undefined" ? window.location.origin : "";
  const url =
    albumId && track.publication_status === "published"
      ? `${origin}/listen/album/${albumId}`
      : origin;
  if (typeof navigator !== "undefined" && navigator.share) {
    await navigator.share({ title: track.title, text, url });
    return;
  }
  if (typeof navigator !== "undefined" && navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(`${text} — ${url}`);
  }
}

export function PublicationDetailPanel({
  track,
  album,
  open,
  onClose,
  onDelete,
  deleting,
}: {
  track: Track | null;
  album?: Album;
  open: boolean;
  onClose: () => void;
  onDelete: (track: Track) => void;
  deleting: boolean;
}) {
  const dialogRef = useRef<HTMLDialogElement>(null);

  useEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;
    if (open && track) {
      if (!dialog.open) dialog.showModal();
    } else if (dialog.open) {
      dialog.close();
    }
  }, [open, track]);

  const handleShare = useCallback(async (t: Track) => {
    try {
      await sharePublication(t, album?.id ?? t.album_id);
    } catch {
      /* annulation partage utilisateur */
    }
  }, [album?.id]);

  if (!track) return null;

  const timeline = buildPublicationLifecycleTimeline(track);
  const autoCover = album ? isAutoGeneratedCover(album) : false;

  return (
    <dialog
      ref={dialogRef}
      className="pub-detail"
      onClose={onClose}
      aria-labelledby="pub-detail-title"
    >
      <div className="pub-detail__sheet">
        <header className="pub-detail__header">
          <button type="button" className="pub-detail__close" onClick={onClose} aria-label="Fermer">
            ✕
          </button>
          <h2 id="pub-detail-title" className="pub-detail__title">
            Fiche publication
          </h2>
        </header>

        <div className="pub-detail__hero">
          <div className="pub-detail__cover">
            {album?.cover_path ? (
              <CoverImage coverPath={album.cover_path} alt={track.title} imgSizes="120px" />
            ) : (
              <span className="pub-detail__cover-placeholder" aria-hidden="true">
                🎵
              </span>
            )}
          </div>
          <div className="pub-detail__meta">
            <p className="pub-detail__track-title">{track.title}</p>
            <PublicationStatusBadge status={track.publication_status} />
            <dl className="pub-detail__facts">
              <div>
                <dt>Durée</dt>
                <dd>{formatTrackDuration(track.duration_seconds)}</dd>
              </div>
              <div>
                <dt>Créée le</dt>
                <dd>{formatPublicationDate(track.created_at)}</dd>
              </div>
              {track.published_at ? (
                <div>
                  <dt>Publiée le</dt>
                  <dd>{formatPublicationDate(track.published_at)}</dd>
                </div>
              ) : null}
            </dl>
            {autoCover ? (
              <p className="pub-detail__hint">Pochette automatique SONAFRIK</p>
            ) : null}
          </div>
        </div>

        <section className="pub-detail__section" aria-labelledby="pub-detail-history">
          <h3 id="pub-detail-history" className="pub-detail__section-title">
            Historique de validation
          </h3>
          <ol className="pub-detail__timeline">
            {timeline.map((event) => (
              <li key={event.id} className="pub-detail__timeline-item">
                <span className="pub-detail__timeline-date">
                  {formatPublicationDate(event.date)}
                </span>
                <span className="pub-detail__timeline-label">{event.label}</span>
                {event.detail ? (
                  <p className="pub-detail__timeline-detail">{event.detail}</p>
                ) : null}
              </li>
            ))}
          </ol>
        </section>

        <PublicationContextualActions
          track={track}
          deleting={deleting}
          onClose={onClose}
          onDelete={onDelete}
          onShare={(t) => void handleShare(t)}
        />
      </div>
    </dialog>
  );
}
