"use client";

import { memo, useCallback } from "react";
import type { Album, Track } from "@sonafrik/types";
import { RELEASE_TYPE_LABELS } from "@sonafrik/types/catalog";
import type { PublicationTrackInsight } from "@sonafrik/api/publication-library";
import {
  formatPublicationDate,
  formatTrackDuration,
} from "@sonafrik/api/publication-library";
import { isAutoGeneratedCover } from "@sonafrik/api/catalog";
import { formatGnf } from "@sonafrik/shared";
import { CoverImage } from "@/components/CoverImage";
import { PublicationStatusBadge } from "./PublicationStatusBadge";
import { PublicationRowActions } from "./PublicationRowActions";

function formatStreams(value: number): string {
  return new Intl.NumberFormat("fr-GN").format(value);
}

function formatRevenue(value: number | null | undefined): string {
  if (value == null || value <= 0) return "—";
  return formatGnf(Math.round(value));
}

function resolveReleaseType(album?: Album): string {
  if (!album) return RELEASE_TYPE_LABELS.single;
  return RELEASE_TYPE_LABELS[album.release_type] ?? RELEASE_TYPE_LABELS.single;
}

function PublicationCardInner({
  track,
  album,
  insight,
  deleting,
  onSelect,
  onDelete,
}: {
  track: Track;
  album?: Album;
  insight?: PublicationTrackInsight;
  deleting: boolean;
  onSelect: (track: Track) => void;
  onDelete: (track: Track) => void;
}) {
  const autoCover = album ? isAutoGeneratedCover(album) : false;
  const handleOpen = useCallback(() => onSelect(track), [onSelect, track]);
  const lastActivity = insight?.last_activity_at ?? track.updated_at;

  return (
    <article className="pub-catalog-row">
      <button
        type="button"
        className="pub-catalog-row__main"
        onClick={handleOpen}
        aria-label={`Ouvrir ${track.title}`}
      >
        <div className="pub-catalog-row__cover">
          {album?.cover_path ? (
            <CoverImage coverPath={album.cover_path} alt="" imgSizes="64px" />
          ) : (
            <span className="pub-catalog-row__cover-placeholder" aria-hidden="true">
              ♪
            </span>
          )}
        </div>

        <div className="pub-catalog-row__identity">
          <p className="pub-catalog-row__title">{track.title}</p>
          <p className="pub-catalog-row__type">{resolveReleaseType(album)}</p>
          {autoCover ? <p className="pub-catalog-row__hint">Pochette automatique</p> : null}
        </div>

        <div className="pub-catalog-row__dates">
          <span className="pub-catalog-row__label">Créé</span>
          <span className="pub-catalog-row__value">{formatPublicationDate(track.created_at)}</span>
          <span className="pub-catalog-row__label">Publié</span>
          <span className="pub-catalog-row__value">
            {track.published_at ? formatPublicationDate(track.published_at) : "—"}
          </span>
        </div>

        <div className="pub-catalog-row__status">
          <PublicationStatusBadge status={track.publication_status} />
        </div>

        <div className="pub-catalog-row__metric">
          <span className="pub-catalog-row__label">Streams</span>
          <span className="pub-catalog-row__value">{formatStreams(insight?.streams ?? 0)}</span>
        </div>

        <div className="pub-catalog-row__metric">
          <span className="pub-catalog-row__label">Revenus</span>
          <span className="pub-catalog-row__value">{formatRevenue(insight?.revenue_gnf)}</span>
        </div>

        <div className="pub-catalog-row__activity">
          <span className="pub-catalog-row__label">Activité</span>
          <span className="pub-catalog-row__value">
            {formatPublicationDate(lastActivity)}
            {track.duration_seconds ? ` · ${formatTrackDuration(track.duration_seconds)}` : ""}
          </span>
        </div>
      </button>

      <div className="pub-catalog-row__actions">
        <PublicationRowActions
          track={track}
          albumId={album?.id ?? track.album_id}
          deleting={deleting}
          onDelete={onDelete}
          onView={onSelect}
        />
      </div>
    </article>
  );
}

export const PublicationCard = memo(PublicationCardInner);
