export { CatalogService, createCatalogService } from "./catalog.service";
export { CatalogRepository } from "./catalog.repository";
export { CatalogError } from "./errors";
export {
  generateDefaultArtwork,
  isAutoGeneratedCover,
  COVER_SOURCE_METADATA_KEY,
  COVER_STATUS,
  coverStatusFromSource,
  type CoverSource,
  type CoverStatus,
  type DefaultArtworkInput,
} from "./artwork";
export {
  MetadataAutomaticEngine,
  wizardUserMetadataSchema,
  type MetadataAutomaticContext,
  type WizardUserMetadataInput,
} from "./metadata";
export {
  createAlbumSchema,
  updateAlbumSchema,
  createTrackSchema,
  updateTrackSchema,
  catalogAssetUploadSchema,
  setTrackCreditsSchema,
  trackCreditItemSchema,
} from "./schemas";
export type {
  CreateAlbumInput,
  UpdateAlbumInput,
  CreateTrackInput,
  UpdateTrackInput,
  CatalogAssetUploadInput,
  SetTrackCreditsInput,
  TrackCreditItem,
} from "./schemas";
export {
  DEFAULT_PUBLICATION_SEARCH_FIELDS,
  DEFAULT_PUBLICATION_SORT,
  normalizePublicationSort,
  parsePublicationLibraryQuery,
  buildPublicationLifecycleTimeline,
  formatPublicationDate,
  formatTrackDuration,
  getPublicationActions,
  getPublicationContinueHref,
  getPublicationCoverHref,
  getPublicationEditHref,
  getPublicationResubmitHref,
  isPublicationEditable,
  isPublicationWithdrawn,
  type PublicationActionDef,
  type PublicationActionId,
  type PublicationLifecycleEvent,
  type PublicationLifecyclePhase,
  type PublicationLibraryQuery,
  type PublicationLibrarySort,
  type PublicationSearchField,
} from "./publication-library";
