/** SONAFRIK — Cover Engine business state (v1.1) */

import type { CoverSource } from "./generateDefaultArtwork";

export const COVER_STATUS = {
  AUTO_GENERATED: "AUTO_GENERATED",
  USER_REPLACED: "USER_REPLACED",
} as const;

export type CoverStatus = (typeof COVER_STATUS)[keyof typeof COVER_STATUS];

export const COVER_STATUS_VALUES = [
  COVER_STATUS.AUTO_GENERATED,
  COVER_STATUS.USER_REPLACED,
] as const;

export type AlbumCoverArtworkView = {
  cover_path?: string | null;
  cover_status?: CoverStatus | string | null;
};

/** Maps technical cover_source to business cover_status. */
export function coverStatusFromSource(source: CoverSource): CoverStatus {
  return source === "auto" ? COVER_STATUS.AUTO_GENERATED : COVER_STATUS.USER_REPLACED;
}

/** Badge « Pochette automatique » — only when business state is AUTO_GENERATED. */
export function isAutoGeneratedCover(album: AlbumCoverArtworkView): boolean {
  if (!album.cover_path?.trim()) return false;
  return album.cover_status === COVER_STATUS.AUTO_GENERATED;
}

export function parseCoverStatus(value: unknown): CoverStatus | null {
  if (value === COVER_STATUS.AUTO_GENERATED || value === COVER_STATUS.USER_REPLACED) {
    return value;
  }
  return null;
}
