/**
 * Shim @sonafrik/api/catalog — Vague I.
 * Publication-library en premier : utilitaires purs client-safe sans charger CatalogService.
 */
export * from "../creator/catalog/publication-library";

export {
  CatalogService,
  createCatalogService,
  CatalogRepository,
  CatalogError,
  generateDefaultArtwork,
  isAutoGeneratedCover,
  COVER_SOURCE_METADATA_KEY,
  COVER_STATUS,
  coverStatusFromSource,
  MetadataAutomaticEngine,
  wizardUserMetadataSchema,
  createAlbumSchema,
  updateAlbumSchema,
  createTrackSchema,
  updateTrackSchema,
  catalogAssetUploadSchema,
  setTrackCreditsSchema,
  trackCreditItemSchema,
} from "../creator/catalog";

export type {
  CoverSource,
  CoverStatus,
  DefaultArtworkInput,
  MetadataAutomaticContext,
  WizardUserMetadataInput,
  CreateAlbumInput,
  UpdateAlbumInput,
  CreateTrackInput,
  UpdateTrackInput,
  CatalogAssetUploadInput,
  SetTrackCreditsInput,
  TrackCreditItem,
} from "../creator/catalog";
