"use client";

import { useEffect, useState } from "react";
import { isAutoGeneratedCover } from "@sonafrik/api/catalog";
import { Badge, Button, Card, CardContent, Input } from "@sonafrik/ui";
import type { Album } from "@sonafrik/types";
import { PUBLICATION_STATUS_LABELS, RELEASE_TYPE_LABELS } from "@sonafrik/types/catalog";
import { FIELD_LIMITS } from "@sonafrik/shared/field-limits";
import { publishCreatorLdseEvent } from "@/features/shared/ldse/creator/publishCreatorLdseEvent";
import { CREATOR_LDSE_EVENTS } from "@/features/shared/ldse/creator/creator-ldse-config";
import { useCatalogService } from "../hooks/useCatalog";
import { useReleasesSrtspLive } from "../hooks/useReleasesSrtspLive";
import { CoverUploader } from "./CoverUploader";
import { CoverImage } from "@/components/CoverImage";
import { ensureAlbumHasCover } from "../lib/ensureAlbumCover";

const UPC_MAX = 14;

function isDeletable(status: Album["publication_status"]): boolean {
  return status === "draft" || status === "rejected";
}

export function ReleaseList({
  albums: initial,
  creatorId,
  stageName,
}: {
  albums: Album[];
  creatorId: string;
  stageName: string;
}) {
  const catalog = useCatalogService();
  const { data: liveAlbums, refresh: refreshReleases } = useReleasesSrtspLive({
    creatorId,
    initialData: initial,
  });
  const [albums, setAlbums] = useState(initial);
  const [title, setTitle] = useState("");
  const [upc, setUpc] = useState("");
  const [loading, setLoading] = useState(false);
  const [expandedCover, setExpandedCover] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [submittingId, setSubmittingId] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [albumAudioReady, setAlbumAudioReady] = useState<Record<string, boolean>>({});

  useEffect(() => {
    if (liveAlbums) setAlbums(liveAlbums);
  }, [liveAlbums]);

  useEffect(() => {
    let cancelled = false;
    const deletable = albums.filter(
      (a) => isDeletable(a.publication_status) && a.release_type === "single",
    );
    if (!deletable.length) return;

    void (async () => {
      const next: Record<string, boolean> = {};
      await Promise.all(
        deletable.map(async (album) => {
          try {
            const tracks = await catalog.listTracks(album.id);
            const track = tracks[0];
            if (!track) {
              next[album.id] = false;
              return;
            }
            const files = await catalog.getTrackFiles(track.id);
            const primary = files.find((f) => f.is_primary);
            next[album.id] = Boolean(primary && primary.integrity_status === "valid");
          } catch {
            next[album.id] = false;
          }
        }),
      );
      if (!cancelled) setAlbumAudioReady(next);
    })();

    return () => {
      cancelled = true;
    };
  }, [albums, catalog]);

  async function createRelease(event: React.FormEvent) {
    event.preventDefault();
    setLoading(true);
    setError(null);
    try {
      const album = await catalog.createAlbum({
        title,
        releaseType: "single",
        upc: upc || null,
      });
      setAlbums((current) => [album, ...current]);
      setTitle("");
      setUpc("");
      publishCreatorLdseEvent(CREATOR_LDSE_EVENTS.catalogInvalidate, creatorId, { albumId: album.id });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Impossible de créer la sortie.");
    } finally {
      setLoading(false);
    }
  }

  async function submit(albumId: string) {
    setSubmittingId(albumId);
    setError(null);
    const album = albums.find((a) => a.id === albumId);
    if (!album) return;
    try {
      await ensureAlbumHasCover(catalog, {
        albumId,
        creatorId,
        trackTitle: album.title,
        artistName: stageName,
      });
      await catalog.submitAlbum(albumId);
      setAlbums((current) =>
        current.map((a) =>
          a.id === albumId ? { ...a, publication_status: "pending_review" } : a,
        ),
      );
      publishCreatorLdseEvent(CREATOR_LDSE_EVENTS.albumPublished, creatorId, { albumId });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Impossible de soumettre cette sortie.");
    } finally {
      setSubmittingId(null);
    }
  }

  async function handleDelete(albumId: string, albumTitle: string) {
    if (!window.confirm(`Supprimer « ${albumTitle} » ? Cette action est irréversible.`)) return;
    setDeletingId(albumId);
    setError(null);
    try {
      await catalog.deleteAlbum(albumId);
      setAlbums((current) => current.filter((a) => a.id !== albumId));
      refreshReleases();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Impossible de supprimer cette sortie.");
    } finally {
      setDeletingId(null);
    }
  }

  return (
    <div className="space-y-6">
      {error ? (
        <p className="text-sm" role="alert" style={{ color: "var(--color-erreur)" }}>
          {error}
        </p>
      ) : null}
      <Card>
        <CardContent className="py-4">
          <form onSubmit={createRelease} className="space-y-3">
            <p className="text-texte-secondaire text-xs">
              MVP : création de singles uniquement. Albums et EP arrivent prochainement.
            </p>
            <div className="space-y-1">
              <Input
                value={title}
                maxLength={FIELD_LIMITS.ALBUM_TITLE}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="Titre du single"
              />
              <div className="flex justify-end">
                <span
                  className="text-xs"
                  style={{ color: title.length > FIELD_LIMITS.ALBUM_TITLE * 0.85 ? "var(--color-or-solaire)" : "var(--color-texte-desactive)" }}
                >
                  {title.length}/{FIELD_LIMITS.ALBUM_TITLE}
                </span>
              </div>
            </div>
            <Input
              value={upc}
              maxLength={UPC_MAX}
              onChange={(e) => setUpc(e.target.value)}
              placeholder="UPC (12-14 chiffres)"
            />
            <Button type="submit" disabled={loading || title.length < 2}>
              Créer un single
            </Button>
          </form>
        </CardContent>
      </Card>

      {albums.map((album) => (
        <Card key={album.id}>
          <CardContent className="space-y-3 py-4">
            <div className="flex flex-wrap items-center gap-2">
              <p className="text-texte-principal font-semibold">{album.title}</p>
              <Badge variant="outline">{RELEASE_TYPE_LABELS[album.release_type]}</Badge>
              <Badge variant="primary">{PUBLICATION_STATUS_LABELS[album.publication_status]}</Badge>
              {isAutoGeneratedCover(album) ? (
                <Badge variant="outline" className="catalog-cover-auto-badge">
                  Pochette automatique
                </Badge>
              ) : null}
            </div>
            {album.release_type !== "single" ? (
              <p className="text-xs" style={{ color: "var(--color-avertissement)" }}>
                Album/EP multi-morceaux : gestion complète bientôt disponible. Utilisez le wizard « Publier un morceau ».
              </p>
            ) : null}
            {album.publication_status === "rejected" && album.rejection_reason && (
              <p className="rounded-lg px-3 py-2 text-xs" style={{ backgroundColor: "var(--overlay-erreur-soft)", color: "var(--color-erreur)" }}>
                <span className="font-semibold">Motif de rejet : </span>{album.rejection_reason}
              </p>
            )}
            {album.upc ? <p className="text-texte-desactive text-xs">UPC · {album.upc}</p> : null}

            {album.cover_path && (
              <div className="h-16 w-16 flex-shrink-0 overflow-hidden rounded-lg">
                <CoverImage coverPath={album.cover_path} alt={album.title} imgSizes="64px" />
              </div>
            )}

            {expandedCover === album.id ? (
              <div className="pt-1">
                <CoverUploader
                  albumId={album.id}
                  creatorId={creatorId}
                  uploadMode="immediate"
                  onSuccess={() => {
                    setExpandedCover(null);
                    publishCreatorLdseEvent(CREATOR_LDSE_EVENTS.catalogInvalidate, creatorId, {
                      albumId: album.id,
                    });
                    refreshReleases();
                  }}
                />
                <button
                  onClick={() => setExpandedCover(null)}
                  className="mt-2 text-xs"
                  style={{ color: "var(--color-texte-desactive)" }}
                >
                  Fermer
                </button>
              </div>
            ) : (
              <div className="flex flex-wrap gap-2">
                <button
                  onClick={() => setExpandedCover(album.id)}
                  className="text-sm hover:underline"
                  style={{ color: "var(--color-vert-energie)" }}
                >
                  {album.cover_path ? "Remplacer la pochette" : "Ajouter / changer la pochette"}
                </button>
                {isDeletable(album.publication_status) && album.release_type === "single" ? (
                  <>
                    {albumAudioReady[album.id] === false ? (
                      <p className="text-xs w-full" style={{ color: "var(--color-avertissement)" }}>
                        Ajoutez un fichier audio validé depuis Mes publications ou le wizard avant de soumettre.
                      </p>
                    ) : null}
                    <Button
                      size="sm"
                      variant="outline"
                      disabled={submittingId === album.id || albumAudioReady[album.id] === false}
                      onClick={() => void submit(album.id)}
                    >
                      {submittingId === album.id ? "Envoi…" : "Soumettre à publication"}
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      disabled={deletingId === album.id}
                      onClick={() => void handleDelete(album.id, album.title)}
                    >
                      {deletingId === album.id ? "Suppression…" : "Supprimer"}
                    </Button>
                  </>
                ) : null}
              </div>
            )}
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
