
import Link from "next/link";
import type { Album, Track } from "@sonafrik/types";
import { PUBLICATION_STATUS_LABELS } from "@sonafrik/types/catalog";
import { buttonVariants } from "@sonafrik/ui";
import { isAutoGeneratedCover } from "@sonafrik/api/catalog";
import { CoverImage } from "@/components/CoverImage";
import { PublicationStatusBadge } from "@/features/creator/publications/components/PublicationStatusBadge";

interface Props {
  track: Track;
  album: Album | null;
  genreName: string | null;
}

export function TrackView({ track, album, genreName }: Props) {
  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="space-y-1">
          <h2 className="text-[var(--t8-pearl)] text-lg font-semibold">{track.title}</h2>
          <PublicationStatusBadge status={track.publication_status} />
        </div>
        <Link href="/creator/catalog/tracks" className={buttonVariants({ variant: "outline", size: "sm" })}>
          â† Retour Ã  la liste
        </Link>
      </div>

      {album?.cover_path ? (
        <div className="h-32 w-32 overflow-hidden rounded-lg">
          <CoverImage coverPath={album.cover_path} alt={album.title} imgSizes="128px" />
        </div>
      ) : null}

      <dl className="space-y-3 text-sm">
        <div>
          <dt className="text-[var(--t8-silver)] text-xs font-semibold uppercase">Statut</dt>
          <dd className="text-[var(--t8-pearl)]">{PUBLICATION_STATUS_LABELS[track.publication_status]}</dd>
        </div>
        {genreName ? (
          <div>
            <dt className="text-[var(--t8-silver)] text-xs font-semibold uppercase">Genre</dt>
            <dd className="text-[var(--t8-pearl)]">{genreName}</dd>
          </div>
        ) : null}
        {track.language ? (
          <div>
            <dt className="text-[var(--t8-silver)] text-xs font-semibold uppercase">Langue</dt>
            <dd className="text-[var(--t8-pearl)]">{track.language.toUpperCase()}</dd>
          </div>
        ) : null}
        {track.duration_seconds ? (
          <div>
            <dt className="text-[var(--t8-silver)] text-xs font-semibold uppercase">DurÃ©e</dt>
            <dd className="text-[var(--t8-pearl)]">
              {Math.floor(track.duration_seconds / 60)}:
              {String(track.duration_seconds % 60).padStart(2, "0")}
            </dd>
          </div>
        ) : null}
        {album && isAutoGeneratedCover(album) ? (
          <div>
            <dt className="text-[var(--t8-silver)] text-xs font-semibold uppercase">Pochette</dt>
            <dd className="text-[var(--t8-pearl)]" style={{ color: "var(--color-or-solaire)" }}>
              Pochette automatique SONAFRIK
            </dd>
          </div>
        ) : null}
      </dl>

      {track.publication_status === "rejected" ? (
        <Link
          href={`/creator/catalog/tracks/${track.id}/edit#publish`}
          className={buttonVariants({ size: "sm" })}
        >
          Corriger et renvoyer
        </Link>
      ) : null}
    </div>
  );
}
