/** Catalogue officiel — aligné DOMAIN_EVENTS.md v2.1.0 */
export type StreamingDomainEventType =
  | "PlaybackRequested"
  | "PlaybackStarted"
  | "PlaybackBuffering"
  | "PlaybackReady"
  | "PlaybackPaused"
  | "PlaybackResumed"
  | "PlaybackSeeked"
  | "PlaybackHeartbeat"
  | "PlaybackCompleted"
  | "PlaybackCancelled"
  | "PlaybackFailed"
  | "SignedUrlIssued"
  | "ConnectionLost"
  | "ConnectionRecovered"
  | "SessionAuthenticated"
  | "SessionCreated"
  | "SessionActivated"
  | "SessionSuspended"
  | "SessionRecovered"
  | "SessionExpired"
  | "SessionClosed"
  | "StreamValidated"
  | "StreamRejected"
  | "AnalyticsUpdated"
  | "FraudSuspected"
  | "FraudConfirmed"
  | "FraudCleared"
  | "LedgerCandidateCreated"
  | "LedgerRecorded"
  | "RoyaltyEligible"
  | "RoyaltyRejected"
  | "RevenueCalculated"
  | "WalletCreditPrepared"
  | "WithdrawalEligible"
  | "NotificationPlaybackFailed"
  | "MonitoringHeartbeatLatency"
  | "MonitoringTransitionRejected"
  | "AuditStreamValidated"
  | "AuditLedgerRecorded";

export const STREAMING_DOMAIN_EVENT_VERSION = "1.0.0" as const;
